#' Export \code{quick_...} output to Excel via \code{openxlsx}
#'
#' @param wb A Workbook object containing a worksheet
#' @param quick_object The output of quick_... command
#'
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx writeData
#' @importFrom openxlsx setColWidths
#' @importFrom openxlsx insertPlot
#' @importFrom showtext showtext_opts
#' @importFrom grDevices dev.off
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # To add
#' }
quick_to_XL <- function(wb, quick_object) {

  class_names <- c("quick_KM",
                   "quick_PH",
                   "quick_fit",
                   "quick_fit_joint",
                   "quick_fit_cure",
                   "quick_fit_splines")

  if (!inherits(quick_object, class_names)) {
    stop(paste0("The quick_to_XL function is only designed for objects",
                "generated by the quick_ function family."),
         call. = FALSE)
  }

  check_classes <- inherits(quick_object,
                            class_names,
                            which = TRUE)

  if (length(which(check_classes != 0)) > 1) {
    stop(paste0("The quick_to_XL function detected multiple ",
                "quick_ function classes. Please provide one object at a time"),
         call. = FALSE)

  }

  class_name <- class_names[[which(check_classes > 0 %in% class_names)]]


  # DPI settings ----

  # Store original DPI
  dpi_R <- showtext::showtext_opts()$dpi

  # Define sufficient resolution for Excel output
  dpi_Excel <- 600

  # Set DPI
  showtext::showtext_opts(dpi = dpi_Excel)

  # ---

  if (class_name == "quick_KM") {

    ## KM summary ----
    sheet_name <- "KM Summary"
    easysurv::add_sheet(wb, sheet_name)

    openxlsx::writeData(
      wb = wb,
      x = quick_object[["KM_summary"]],
      sheet = sheet_name,
      startCol = 2,
      startRow = 2
    )

    options("openxlsx.minWidth" = 5)
    #openxlsx::setColWidths(wb, sheet_name, cols = 1:10, widths = "auto")


    ## Stepped KMs ----
    sheet_name <- "Stepped KMs"
    easysurv::add_sheet(wb, sheet_name)

    for (KM in seq_along(quick_object$KM_stepped)) {
      # KM names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object[["KM_stepped"]])[[KM]],
        sheet = sheet_name,
        startCol = 2 + (KM - 1) * 5,
        startRow = 2
      )

      # Actual KM
      openxlsx::writeData(
        wb = wb,
        x = quick_object[["KM_stepped"]][[KM]],
        sheet = sheet_name,
        startCol = 2 + (KM - 1) * 5,
        startRow = 3
      )
    }

    ## KM Plot
    sheet_name <- "KM Plot"
    easysurv::add_sheet(wb, sheet_name)

    # The plot needs to be showing for insertPlot to work.
    suppressWarnings(print(quick_object$KM_plot))
    openxlsx::insertPlot(wb, sheet_name,
                         width = 8,
                         height = 6,
                         startRow = 2,
                         startCol = 2,
                         fileType = "png", units = "in",
                         dpi = dpi_Excel
    )

    # ---
    # Restore DPI
    showtext::showtext_opts(dpi = dpi_R)

    # Clear plot
    grDevices::dev.off()

    # Re-print
    suppressWarnings(print(quick_object$KM_plot))
  }


  if (class_name == "quick_PH") {

    sheet_name <- "PH Plots"
    easysurv::add_sheet(wb, sheet_name)

    suppressWarnings(print(quick_object$cloglog_plot))
    openxlsx::insertPlot(wb, sheet_name,
                         width = 8,
                         height = 6,
                         startRow = 2,
                         startCol = 2,
                         fileType = "png", units = "in",
                         dpi = dpi_Excel
    )

    suppressWarnings(print(quick_object$schoenfeld_plot))
    openxlsx::insertPlot(wb, sheet_name,
                         width = 8,
                         height = 6,
                         startRow = 2,
                         startCol = 12,
                         fileType = "png", units = "in",
                         dpi = dpi_Excel
    )

    # Restore DPI
    showtext::showtext_opts(dpi = dpi_R)

    # Clear plot
    grDevices::dev.off()

    # Re-print
    suppressWarnings(print(quick_object$cloglog_plot))
    suppressWarnings(print(quick_object$schoenfeld_plot))
  }



  # quick_fit_... objects
  if (!class_name == "quick_KM" & !class_name == "quick_PH") {

    sheet_name <- switch(class_name,
                         "quick_fit" = "Standard - Hazard Plots",
                         "quick_fit_joint" = "Joint - Hazard Plots",
                         "quick_fit_cure" = "MCM - Hazard Plots",
                         "quick_fit_splines" = "Splines - Hazard Plots")

    easysurv::add_sheet(wb, sheet_name)

    for (plot_id in seq_along(quick_object$hazard_plots)) {
      suppressWarnings(print(quick_object$hazard_plots[[plot_id]]))

      openxlsx::insertPlot(wb, sheet_name,
                           width = 8,
                           height = 6,
                           startRow = 2,
                           startCol = 2 + (plot_id - 1) * 10,
                           fileType = "png", units = "in",
                           dpi = dpi_Excel)
    }

    sheet_name <- switch(class_name,
                         "quick_fit" = "Standard - Fit Plots",
                         "quick_fit_joint" = "Joint - Fit Plots",
                         "quick_fit_cure" = "MCM - Fit Plots",
                         "quick_fit_splines" = "Splines - Fit Plots")

    easysurv::add_sheet(wb, sheet_name)

    for (plot_id in seq_along(quick_object$fit_plots)) {
      print(quick_object$fit_plots[[plot_id]])

      openxlsx::insertPlot(wb, sheet_name,
                           width = 8,
                           height = 6,
                           startRow = 2,
                           startCol = 2 + (plot_id - 1) * 10,
                           fileType = "png", units = "in",
                           dpi = dpi_Excel
      )
    }

    # Restore DPI
    showtext::showtext_opts(dpi = dpi_R)

    # Clear plot
    grDevices::dev.off()

    # Re-print the plots
    # This seems to help with font sizing in Excel of subsequent plots
    # The DPI functionality may rely on there being an active plot.
    for (plot_id in seq_along(quick_object$hazard_plots)) {
      suppressWarnings(print(quick_object$hazard_plots[[plot_id]]))
    }

    for (plot_id in seq_along(quick_object$fit_plots)) {
      suppressWarnings(print(quick_object$fit_plots[[plot_id]]))
    }


    sheet_name <- switch(class_name,
                         "quick_fit" = "Standard - Fit Stats",
                         "quick_fit_joint" = "Joint - Fit Stats",
                         "quick_fit_cure" = "MCM - Fit Stats",
                         "quick_fit_splines" = "Splines - Fit Stats")
    easysurv::add_sheet(wb, sheet_name)

    for (tx in seq_along(quick_object$goodness_of_fit)) {
      # tx names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object$goodness_of_fit[tx]),
        sheet = sheet_name,
        startCol = 2 + (tx - 1) * 7,
        startRow = 2
      )

      # goodness_of_fit dataframe
      openxlsx::writeData(
        wb = wb,
        x = quick_object$goodness_of_fit[[tx]],
        sheet = sheet_name,
        startCol = 2 + (tx - 1) * 7,
        startRow = 3
      )
    }

    sheet_name <- switch(class_name,
                         "quick_fit" = "Standard - Fit Averages",
                         "quick_fit_joint" = "Joint - Fit Averages",
                         "quick_fit_cure" = "MCM - Fit Averages",
                         "quick_fit_splines" = "Splines - Fit Averages")
    easysurv::add_sheet(wb, sheet_name)

    for (tx in seq_along(quick_object$fit_averages)) {
      # tx names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object$fit_averages[tx]),
        sheet = sheet_name,
        startCol = 2 + (tx - 1) * 14,
        startRow = 2
      )

      # fit_averages dataframe
      openxlsx::writeData(
        wb = wb,
        x = quick_object$fit_averages[[tx]],
        sheet = sheet_name,
        startCol = 2 + (tx - 1) * 14,
        startRow = 3
      )
    }


    for (tx in seq_along(quick_object$surv_params)) {
      sheet_name <- switch(class_name,
                           "quick_fit" = "Standard - Surv Params ",
                           "quick_fit_joint" = "Joint - Surv Params ",
                           "quick_fit_cure" = "MCM - Surv Params ",
                           "quick_fit_splines" = "Splines - Surv Params ")
      sheet_name <- paste0(sheet_name, tx)
      easysurv::add_sheet(wb, sheet_name)

      # tx names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object$surv_params[tx]),
        sheet = sheet_name,
        startCol = 2,
        startRow = 2
      )
      # surv_params dataframe
      openxlsx::writeData(
        wb = wb,
        x = as.data.frame(quick_object$surv_params[[tx]]),
        sheet = sheet_name,
        startCol = 2,
        startRow = 3
      )

      options("openxlsx.minWidth" = 10)
      #openxlsx::setColWidths(wb, sheet_name, cols = 1:20, widths = "auto")
    }



    for (tx in seq_along(quick_object$predicted_fits)) {
      sheet_name <- switch(class_name,
                           "quick_fit" = "Standard - Predictions ",
                           "quick_fit_joint" = "Joint - Predictions ",
                           "quick_fit_cure" = "MCM - Predictions ",
                           "quick_fit_splines" = "Splines - Predictions ")
      sheet_name <- paste0(sheet_name, tx)
      easysurv::add_sheet(wb, sheet_name)

      # tx names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object$predicted_fits[tx]),
        sheet = sheet_name,
        startCol = 2,
        startRow = 2
      )


      # predicted_fits dataframe
      openxlsx::writeData(
        wb = wb,
        x = quick_object$predicted_fits[[tx]],
        sheet = sheet_name,
        colNames = TRUE,
        startCol = 2,
        startRow = 3
      )
    }

  }

  if (class_name == "quick_fit_cure") {
    sheet_name <- "MCM - Cure Fractions"
    easysurv::add_sheet(wb, sheet_name)

    for (tx in seq_along(quick_object$cure_fractions)) {
      # tx names
      openxlsx::writeData(
        wb = wb,
        x = names(quick_object$cure_fractions[tx]),
        sheet = sheet_name,
        startCol = 2 + (tx - 1) * 5,
        startRow = 2
      )


      # cure_fractions dataframe
      openxlsx::writeData(
        wb = wb,
        x = t(as.data.frame(quick_object$cure_fractions[[tx]])),
        sheet = sheet_name,
        rowNames = TRUE,
        colNames = FALSE,
        startCol = 2 + (tx - 1) * 5,
        startRow = 3
      )
    }

  }

  invisible()
}
